language: ruby
rvm:
- 2.3.0
notifications:
  email:
    recipients:
    - cas.eliens@gmail.com
    on_success: change
    on_failure: change
script: bundle exec rake
before_install:
- gem update --system
services:
- redis-server
deploy:
  provider: rubygems
  api_key:
    secure: "xEC9fzPXl1/la7ONuPipqXpbOEpA3GhIm+Dc74OPl20+RbOjHGmhRWOQWi4DCX/zNnWFKnIPxp0NMT2mW28hqRZBaUPKj9jN3AnrJ6EgWOaaWkAkwhXBou16+5Xgz2U8K7TB/CFIv41avONQJxUUITEKF+6+7U25ixkbbPeMttMOSx4WrlJmSfR2bz3LyCdniK3EyD7wTGz6FWpPIjdV3ZApJDL+/0yFm6hrilsq3aMtnrdaGdQ+tQtSNlT/PhBtRYkQs+0WlkmHfUaS3EDHbGw9vI2NBmp7EoPnmKNbyHmHb6EyXa8X/oMFvhwVoaRE8Gw5jkJJthCDTsfuTUq7s90/URwtCPGBs+eP1FQROBnw55oH2lBzoZ98l3p/7+T3QHKlQRRjr3XP4FkyxF/hiOylBk6COWLfDQqijmmSWfgeGykyo4Vk8jvV820HpOa95GmrB+k1qPPgezJi9kC/8rIzKV0LhqlmNuGqtWTAFFPqnM4Lo7pCfw1tRxyITQ3xObr/xRLHcgKr6ZMg5SwgN/Qrc8FXD31c77kaVUQg4dJSUSo9OAwrKprqC0tvUprIknXoXTpfxaYUKr9yPSBdXUGgidZTjA6kHdo0VXt3kPJXlccN+YzLsRgmq+k2XXoDncLhYTAQN6KaCLCnGX/OCBKVhFUnALLp95djdH1gYQg="
  gem: lita-diabetter
  on:
    all_branches: true
